Reaggregate completions for target user
ndunand/moodle-tool_mergeusers pull request #175
Opened 2020-05-11 10:22 UTC by andrewhancox

Course completions are currently not being re-calculated once the user is merged.

If between the combined activity of two accounts the completion requirements of a course are satisfied the user will not be marked as complete. This was also causing Issue 131.

2021-06-10 20:26 UTC, jpahullo commented
Hi @andrewhancox !

Sorry for so much time. I can forsee a bit of time for updating this plugin.

I made you some suggestions. Do you think you could update your PR in the line I propose? I didn't check it's working.

Thanks for your time!

I look forward seeing your new patch ;-)

2021-06-10 20:30 UTC, andrewhancox commented
Apologies if I'm missing something obvious but I can't see any comments on my PR...

2021-06-10 22:07 UTC, jpahullo requested changes

2021-06-10 22:08 UTC, jpahullo commented
Sorry @andrewhancox , I forgot to complete the form with my reviews here. Now you should see them. Thanks for your time!

And, for sure, there is nothing to sorry! Thanks a lot to you!

2021-07-02 15:15 UTC, jpahullo commented
Hi @andrewhancox, do you think you could test the proposal and update the patch? Thank you a lot for your time!

2021-07-05 11:06 UTC, andrewhancox commented
I don’t necessarily agree with the changes you have suggested - I feel that the mark_inprogress API call is intended to mark a course as in progress, not prompt a reaggregation of existing data, and so wouldn’t necessarily view it as the right call to make in the scenario.

If you disagree then that’s fair enough but due to the overhead of testing this functionality properly I don’t currently have time to make the changes.

> On 2 Jul 2021, at 16:15, Jordi Pujol-Ahulló ***@***.***> wrote:
> 
> 
> Hi @andrewhancox <https://github.com/andrewhancox>, do you think you could test the proposal and update the patch? Thank you a lot for your time!
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/ndunand/moodle-tool_mergeusers/pull/175#issuecomment-873073837>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AAJEYMQJ2MWA2XU6PH56XQTTVXJZRANCNFSM4M5Y7L6Q>.
>

2021-07-14 20:48 UTC, jpahullo commented
Thanks for your contribution @andrewhancox ! You made me think about it and so, it will require more time to check it out. 

Since it is working for you, and I do not see any inconvenient right now, I move forward this PR and I'll create an issue to check this completion API later on.

2021-07-14 20:49 UTC, jpahullo commented on lib/mergeusertool.php
> +        $DB->execute(
As I comment in this PR, I'll check this API in another issue.

2021-07-14 20:50 UTC, jpahullo approved these changes

2021-07-14 20:50 UTC, merged