Search by custom user profile fields
ndunand/moodle-tool_mergeusers pull request #231
Opened 2022-12-22 23:11 UTC by Tsheke

Hi @ndunand ,

Would you like to merge this request please? We added support to make search by custom user profile fields:

- Settings support to allow search by custom user profile fields and to select desired fields.
- Support to make search by desired fields.
- Support to make direct search by desired field.
- If 'none' (default choice) is selected in the settings, the plugin should work without custom user profile support. 

How to test the new fonctionnality:

- Create  some custom user profile fields.
- Set values on some fields for desired users.
- Go to the mergeusers plugin settings and select one or more fields for which you wish to allow search.
- Open the mergeusers page and it should display options to make search by custom user profile fields allowed.
- With the search result, the process of merging users continue as usually.

Thank you.

2022-12-22 23:18 UTC, Tsheke commented
mergeusers form screenshots

2023-04-04 22:20 UTC, jpahullo commented
Thanks @Tsheke for your contribution. 

It seems quite good.

However, before integrating your PR into this plugin, please, consider the following comments and ammendments suggestions:

1. index_form.php and profile fields: `user_filter_profilefield::get_profile_fields()` always return a first element named `0 => 'any field'`. This item is also present on the plugin settings. So:
   1. When setting `any field` in the plugin settings, index_form.php should consider any existing profile field.
   2. If `user_filter_profilefield::get_profile_fields()` only returns an array of one element `0 => 'any field'`, this should be considered as additional profile field is not available. settings.php should show only `None` and nothing else.
   3. If `user_filter_profilefield::get_profile_fields()` returns more than one element, and in settings.php is selected `any field` (value `0`), index_form.php should gather all real profile fields from `user_filter_profilefield::get_profile_fields()` (excluding `0 => 'any field'` as if admin selected all existing profile fields from the list.
   4. index_form.php:77: `$advanced` is undefined. I suppose you meant to be `true`.
1. Since you have modified settings.php, you need to update version.php to bump up its version. Consider only the version on the current master branch. I had to do this when testing locally.
2. Syntax have to be revisited. Please, use tools like local_codechecher Moodle plugin to validate that your code follows Moodle code conventions. At least, your modified parts of the document. Please, do no alter parts of a document just for syntax correction. Just your own parts, the parts you contribute in this PR. There are so many bits to fix.
3. Revisit code twice again, to fix any problematic item. For instance, there is some comment that seems to comment out a pre-existing line, like [this](https://github.com/ndunand/moodle-tool_mergeusers/pull/231/files#diff-8f5ff72ef1cf59199cfc4bbf16f2475d09e448601242f0d2c51bb94bd4aa1395R87).

In addition, I think we could improve your proposal by adding any allowed user profile field to be added into the existing initial selector, as with the rest `Idnumber`, `Email address` and so on. The name could be of the form `profile_field_3`, visible name `Custom profile 1` and value `search pattern`, when looking for the user profile field with id = 3 (i.e., having `profile_field_` as prefix always, and `3` or any given number, as the field id). Then, when submitting the form, we would look into the pattern `profile_field_` and if match we will take the given number as the field.id being search by.

This way, this part would not be hidden as an advanced item, but as a main part, included into the existing selector for id, idnumber, email and so on. I think it would be very benefitial for admin users indeed.

Let me know if you can afford this change.

Thanks for your contribution,

Jordi

2023-04-04 22:22 UTC, jpahullo commented
By the way, 

Please, @Tsheke, add some PHPUnit tests to validate your new part. Thanks!

Jordi

2023-04-18 21:36 UTC, Tsheke commented
Hi @jpahullo ,
Thanks you for the feedback. I made changes you suggested. Some variables was renammed for validation with the codechecker. This is mainly removing Camel Style and/or underscrore to have all in lower case.
For the last improvement you suggeted, it's a good idea, but we can check it later when we get some free time. I could add the PHP unit test later too.

Thank you so much and let me know what you think about the pull request.
Johnny.

2023-04-19 08:51 UTC, jpahullo requested changes

2023-04-19 08:51 UTC, jpahullo commented on settings.php
> +    $profilefieldsoptions = tool_mergeusers_build_profilefields_options();
This setting calculates all options always. Settings like this should be made lazy: I mean, load options only when this setting is really shown by a user.

One way is this: https://github.com/jpahullo/moodle/commit/9c4510a358cdcd192085d8d96c99acc571292dac. But look at some other admin setting that loads options only whenever used, with the same idea: is there no option already? calculate and return. To do so, I think you have to build a new class for this admin setting. 

Thanks.

2023-04-19 08:51 UTC, jpahullo commented on settings.php
> +    //
Remember that I said you shoundn't have to update existing code, only your new code. I made it explicit.  Leave  this comment as a multiline phpdoc comment, please. It's useful for IDEs. 

And many thanks for all the revision of existing code checkings ;-)

2023-04-19 08:52 UTC, jpahullo commented
Once you @Tsheke  make the requested changes, we will run the workflow to make the latest checkings.

Please, add tests for this profile fields part too.

2023-10-06 00:40 UTC, Tsheke commented
Hi @jpahullo ,
Here are changes you requested + php unit test.
Would you like to have look please?
Thank you.

2023-11-29 22:26 UTC, jpahullo approved these changes

2023-11-29 22:30 UTC, jpahullo commented
Hi @Tsheke,

Thanks for the effort. 

It seems quite good right now. You do not considered a comment about the settings.php file though.

In addition, I have to test it locally and validate the whole solution. I will be back once I can with more information.

Thanks again,

Jordi

2025-03-28 16:40 UTC, Tsheke commented
Hi @jpahullo ,
Did you get time to look at this pull request please? How can I help?

2025-08-14 10:34 UTC, closed without merging